name: orbit
description: Orbit – Fortnite & BO7 Tracker
publish_to: "none"

version: 0.2.0-beta+4

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Link öffnen
  url_launcher: ^6.3.0

  # Version automatisch aus App-Metadaten lesen
  package_info_plus: ^8.0.2

  # HTTP für Update-Check (JSON laden + Download)
  http: ^1.2.2

  # APK speichern
  path_provider: ^2.1.4

  # APK öffnen (Installer)
  open_filex: ^4.5.0

  # Offline-Speicher (Häkchen etc.)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # App Icon Generator
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/icon/   # <- empfehle ich, wenn du icons dort liegen hast

flutter_launcher_icons:
  android: true
  adaptive_icon_background: "#12002b" # dunkles lila/schwarz
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
  image_path: "assets/icon/app_icon.png"